from django.conf.urls import patterns, include, url
from .views import *

urlpatterns = patterns('',
	url(r'^control_main/$' , 'principal.control.views.control_main'),
	url(r'^buscarprof/$' , 'principal.control.views.buscarprof'),
	url(r'^mostrarprofesores/$' , 'principal.control.views.mostrarprofesores'),
	url(r'^eliminarprofesor([\w|\W]+)/$' , 'principal.control.views.eliminarprofesor'),		
	url(r'^eliminar_total/$' , 'principal.control.views.eliminartotalprofesor'),
	url(r'^fechas_inscripciones/$' , 'principal.control.views.fechas_inscripciones'),
	url(r'^fechas_ord/$' , 'principal.control.views.fechas_ordinarias'),	
	url(r'^guardar_inscripciones/$' , 'principal.control.views.guardar_inscripciones'),	
	url(r'^modificar_inscripciones/$' , 'principal.control.views.modificar_inscripciones'),	
	url(r'^modificar_ordinarias/$' , 'principal.control.views.modificar_ordinarias'),	
	url(r'^guardar_ordinarias/$' , 'principal.control.views.guardar_ordinarias'),
	url(r'^fechas_extra/$' , 'principal.control.views.fechas_extra'),	
	url(r'^modificar_extraordinarias/$' , 'principal.control.views.modificar_extraordinarias'),	
	url(r'^guardar_extraordinarias/$' , 'principal.control.views.guardar_extraordinarias'),
	url(r'^fechas_ets/$' , 'principal.control.views.fechas_ets'),	
	url(r'^modificar_ets/$' , 'principal.control.views.modificar_ets'),
	url(r'^guardar_ets/$' , 'principal.control.views.guardar_ets'),
	url(r'^documentos/$' , 'principal.control.views.documentos'),
	url(r'^eliminardocumento([\w|\W]+)/$' , 'principal.control.views.eliminardocumento'),	
	url(r'^eliminar_documento/$' , 'principal.control.views.eliminartotaldocumento'),
	url(r'^regMateria/$' , 'principal.control.views.regMateria'),
	url(r'^abreMateria/$' , 'principal.control.views.abreMateria'),
	url(r'^abreBuscaMateria/$' , 'principal.control.views.abreBuscaMateria'),
	url(r'^mostrarprofesores/$' , 'principal.control.views.mostrarprofesores'),
	url(r'^mostrarMateria/$' , 'principal.control.views.mostrarMateria'),
	url(r'^eliminarprofesor(\d*)/$' , 'principal.control.views.eliminarprofesor'),
	url(r'^eliminar_total/$' , 'principal.control.views.eliminartotalprofesor'),
	url(r'^abreModificaMateria/$' , 'principal.control.views.abreModificaMateria'),
	url(r'^modificaMateria/$' , 'principal.control.views.modificaMateria'),
	url(r'^periodo_escolar/$' , 'principal.control.views.periodo_escolar'),
	url(r'^modificar_periodo/$' , 'principal.control.views.modificar_periodo'),
	url(r'^guardar_periodo/$' , 'principal.control.views.guardar_periodo'),
	url(r'^alumnoCorreo/$' , 'principal.control.views.alumnoCorreo'),
	url(r'^enviarAlumnoCorreo/$' , 'principal.control.views.enviarAlumnoCorreo'),
	url(r'^buscarAlum/$' , 'principal.control.views.buscarAlum'),
	url(r'^mostrarAlum/$' , 'principal.control.views.mostrarAlum'),
	url(r'^reporteAlum/$' , 'principal.control.views.reporteAlum'),
	url(r'^regAlumno/$' , 'principal.control.views.regAlumno'),
	url(r'^modificarAlum/$' , 'principal.control.views.modificarAlum'),
	url( r'^grupos/$',						'principal.control.views.gestion_grupos'				),
	url( r'^abrir_grupo/$',					'principal.control.views.abrir_grupo'					),
	url( r'^modificar_grupo([\w|\W]+)/$',	'principal.control.views.modificar_grupo'				),
	url( r'^consultar_grupo([\w|\W]+)/$',	'principal.control.views.controlador_consultar_grupo'	),
	url( r'^cerrar_grupo([\w|\W]+)/$',		'principal.control.views.controlador_cerrar_grupo'		),

	url( r'^c_abrir_grupo/$',		'principal.control.views.controlador_abrir_grupo'		),
	url( r'^c_modificar_grupo/$',		'principal.control.views.controlador_modificar_grupo'		),
	url(r'^modificarprofesor([\w|\W]+)/$' , 'principal.control.views.modificarprofesor'),	
	url(r'^Agregar_modificar_profesor/$' , 'principal.control.views.nuevoprof'),
	url(r'^agregar_nuevo/$' , 'principal.control.views.agregar_nuevo_prof'),
	url(r'^modificar_prof/$' , 'principal.control.views.modificar_prof'),
	url(r'^darBajaMat/$' , 'principal.control.views.darBajaMat'),
	url(r'^darDeBaja/$' , 'principal.control.views.darDeBaja'),
	url(r'^agregarmateria([\w|\W]+)/$' , 'principal.control.views.agregarmateria'),		
	url(r'^agregarhorario([\w|\W]+)/$' , 'principal.control.views.agregarhorario'),	
	url(r'^alumnoKardex/$' , 'principal.control.views.alumnoKardex'),
	
)
